[env:esp32-c3-supermini]
; 强行锁死环境为 LTS ESP-IDF v5.1.4 稳定版环境
platform = espressif32 @ 6.7.0
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200

; 锁死物理开发板的闪存参数
board_upload.flash_size = 4MB
board_build.flash_mode = dio

; 强行锁定 USB 原生物理串口
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*

build_flags =
; 💥 【已去除 -Os 优化】：保留最原始的 C 语言函数调用栈，方便死锁调试
    -D CORE_DEBUG_LEVEL=5          ; 💥 【已改为最高级别 5】：全面开启 VERBOSE 底层微观硬件全日志输出
