[env:esp32-c3-supermini]
platform = espressif32 @ 6.9.0
board = esp32-c3-devkitm-1
framework = espidf
monitor_speed = 115200

; 强行锁定 Mac 的 USB 串口，跳过蓝牙
upload_port = /dev/cu.usbmodem*
monitor_port = /dev/cu.usbmodem*

build_flags =
    -Os
    -D CORE_DEBUG_LEVEL=3
