[env:beetle_esp32c6]
platform = espressif32 @ 6.9.0
framework = espidf
board = esp32-c6-devkitc-1
monitor_speed = 115200

# 覆盖板级 JSON 配置，强制声明物理 Flash 大小
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
monitor_filters = direct
